### ISSUE TITLE
[Feature] Ignore indicators when scaling y-axis

### ISSUE THREAD

**Issue by jinusean** [klinecharts/KLineChart#513]
### Feature Description

Scale y-axis to only candles (ignore indicators).

Currently with indicator (blue line)
![image](https://github.com/liihuu/KLineChart/assets/6874981/e00d2cf9-e0c1-4a88-b35e-d28cbad87c0a)

Without indicator:
![image](https://github.com/liihuu/KLineChart/assets/6874981/94202297-ebf9-4f9c-89fb-0fbccd24cee8)

Desired effect:
Keep indicator on chart but scale y-axis as if it wasn't there.

### To Do

1. Set option somewhere to scale only candles

**Comment by char101** [comment]
If an indicator has no figure it will not be included in the scaling so you could just custom draw your vwap indicator using canvas path.

**Comment by jinusean** [comment]
Thanks for the tip but I was hoping for a more API driven approach.

**Comment by jinusean** [comment]
@char101 noticed even in the preview there's a lot of padding

![image](https://github.com/klinecharts/KLineChart/assets/6874981/a4655ded-8445-4f21-b26b-8953790ce3cc)

**Comment by char101** [comment]
That's because when scrolling past the data end, the visible data list doesn't change. The min and max of the yaxis is calculated from the visible data list.

For example if you change `i = from` to `i = Math.max(from, realFrom)` in https://github.com/klinecharts/KLineChart/blob/main/src/store/ChartStore.ts#L111 you will get scaling.
